---
title: "susie_summary"
author: "Yunqi Yang"
date: "7/5/2024"
output: html_document
---

```{r}
library(survival)
library(susieR)
devtools::load_all("/Users/nicholeyang/Downloads/logisticsusie")
```

```{r}
regions = c("chr11_75500001_77400000", 
            "chr12_46000001_48700000",
            "chr17_33500001_39800000",
            "chr10_6600001_12200000",
            "chr1_150600001_155100000",
            "chr15_59000001_63400000",
            "chr2_102100001_105300000",
            "chr2_143400001_147900000")

region_name = c("11q13.5", "12q13.1", "17q12", "10p14", "1q21.3", "15q22.2", "2q12.1", "2q22.3")


analysis = c("AA", "AOA", "COA", "AA", "COA", "AA", "AA", "AOA")
summary = data.frame(cbind(regions, analysis))
cols = c("#D63440", "#5584B0","#F8A254", "#449559", "#B57BA2", "#FFE53C")
```


```{r}
cs_summary <- c()
for (i in 1:nrow(summary)){
  
  region = summary$region[i]
  analysis = summary$analysis[i]
  
  if (analysis == "AA"){
    # gwas results
    gwas.survival = data.frame(readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/all_gwas_", region, ".rds")))
    # finemapping results
    res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/all/fit.susie.", region, ".rds"))
  }

  if (analysis == "COA"){
    gwas.survival = data.frame(readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/coa_gwas_", region, ".rds")))
    res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/coa/fit.susie.", region, ".rds"))
  }
  
  if (analysis == "AOA"){
    gwas.survival = data.frame(readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/aoa_gwas_", region, ".rds")))
    res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/aoa/fit.susie.", region, ".rds"))
  }
  
  

  fit = res[[1]]
  X = res[[2]]
  
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  if (!is.null(cs$cs)){
    for (i in 1:length(cs$cs)){
    size = length(cs$cs[[i]])
    snps = colnames(X)[cs$cs[[i]]]
    gwas.sub = gwas.survival[rownames(gwas.survival) %in% snps, ]
    indx = which.min(gwas.sub$p.value.spa)
    pval = gwas.sub$p.value.spa[indx]
    top_snp = rownames(gwas.sub)[indx]
    output = c(region, analysis, size, as.numeric(cs$purity[i, "min.abs.corr"]), top_snp, -log10(pval))
    cs_summary = rbind(output, cs_summary) 
    }
  }
  rm(res, fit, X, gwas.survival)
}
```


```{r}
colnames(cs_summary) = c("region", "analysis", "size", "min.abs.corr", "variant", "neg.log10_pval")
rownames(cs_summary) <- NULL
cs_summary = data.frame(cs_summary)
cs_summary$size = as.numeric(cs_summary$size)
cs_summary$min.abs.corr = round(as.numeric(cs_summary$min.abs.corr), 2)
cs_summary$neg.log10_pval = round(as.numeric(cs_summary$neg.log10_pval), 2)


write.csv(cs_summary, "/Users/nicholeyang/Downloads/survival-data-analysis/output/cs_summary.csv")

```

```{r fig.height = 16, fig.width = 10}
pdf("/Users/nicholeyang/Downloads/survival-data-analysis/output/susie1.pdf", width = 10, height = 13)
layout(matrix(1:12, ncol = 3, byrow = TRUE))
for (i in 1:4){
  # AA
  region = regions[i]
  res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/all/fit.susie.", region, ".rds"))
  gwas = readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/all_gwas_", region, ".rds"))
  fit = res[[1]]
  X = res[[2]]
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  
  colors = rep("#C3C3C3", nrow(gwas))
  pvals = -log10(gwas[, "p.value.spa"])
  plot(pvals, col = colors, xlab = "SNP", ylab = "-log10(p-value)", cex = 0.8, pch = 20, main = paste0(region_name[i], ": AA"), ylim = c(0, max(pvals, na.rm = TRUE)+0.1))
  
  for (j in 1:length(cs$cs)){
    snps = colnames(X)[cs$cs[[j]]]
    indx = which(rownames(gwas) %in% snps)
    colors[indx] = cols[j]
    points(indx, -log10(gwas[indx, "p.value.spa"]), col = cols[j], pch = 20)
  }
  
  
  rm(gwas, res, X, fit)
  
  # COA
  res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/coa/fit.susie.", region, ".rds"))
  gwas = readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/coa_gwas_", region, ".rds"))
  fit = res[[1]]
  X = res[[2]]
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  
  colors = rep("#C3C3C3", nrow(gwas))
  pvals = -log10(gwas[, "p.value.spa"])
  plot(pvals, col = colors, xlab = "SNP", ylab = "-log10(p-value)", cex = 0.8, pch = 20, main = paste0(region_name[i], ": COA"), ylim = c(0, max(pvals, na.rm = TRUE)+0.1))
  
  for (j in 1:length(cs$cs)){
    snps = colnames(X)[cs$cs[[j]]]
    indx = which(rownames(gwas) %in% snps)
    colors[indx] = cols[j]
    points(indx, -log10(gwas[indx, "p.value.spa"]), col = cols[j], pch = 20)
  }
  
  rm(gwas, res, X, fit)
  
  # AOA
  res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/aoa/fit.susie.", region, ".rds"))
  gwas = readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/aoa_gwas_", region, ".rds"))
  fit = res[[1]]
  X = res[[2]]
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  
  colors = rep("#C3C3C3", nrow(gwas))
  pvals = -log10(gwas[, "p.value.spa"])
  plot(pvals, col = colors, xlab = "SNP", ylab = "-log10(p-value)", cex = 0.8, pch = 20, main = paste0(region_name[i], ": AOA"), ylim = c(0, max(pvals, na.rm = TRUE)+0.1))
  for (j in 1:length(cs$cs)){
    snps = colnames(X)[cs$cs[[j]]]
    indx = which(rownames(gwas) %in% snps)
    colors[indx] = cols[j]
    points(indx, -log10(gwas[indx, "p.value.spa"]), col = cols[j], pch = 20)
  }
  rm(gwas, res, X, fit)
}
```


```{r fig.height = 16, fig.width = 10}
pdf("/Users/nicholeyang/Downloads/survival-data-analysis/output/susie2.pdf", width = 10, height = 13)
layout(matrix(1:12, ncol = 3, byrow = TRUE))
for (i in 5:8){
  # AA
  region = regions[i]
  res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/all/fit.susie.", region, ".rds"))
  gwas = readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/all_gwas_", region, ".rds"))
  fit = res[[1]]
  X = res[[2]]
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  
  colors = rep("#C3C3C3", nrow(gwas))
  pvals = -log10(gwas[, "p.value.spa"])
  plot(pvals, col = colors, xlab = "SNP", ylab = "-log10(p-value)", cex = 0.8, pch = 20, main = paste0(region_name[i], ": AA"), ylim = c(0, max(pvals, na.rm = TRUE)+0.1))
  for (j in 1:length(cs$cs)){
    snps = colnames(X)[cs$cs[[j]]]
    indx = which(rownames(gwas) %in% snps)
    colors[indx] = cols[j]
    points(indx, -log10(gwas[indx, "p.value.spa"]), col = cols[j], pch = 20)
  }
  rm(gwas, res, X, fit)
  
  # COA
  res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/coa/fit.susie.", region, ".rds"))
  gwas = readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/coa_gwas_", region, ".rds"))
  fit = res[[1]]
  X = res[[2]]
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  
  colors = rep("#C3C3C3", nrow(gwas))
  pvals = -log10(gwas[, "p.value.spa"])
  plot(pvals, col = colors, xlab = "SNP", ylab = "-log10(p-value)", cex = 0.8, pch = 20, main = paste0(region_name[i], ": COA"), ylim = c(0, max(pvals, na.rm = TRUE)+0.1))
  
  for (j in 1:length(cs$cs)){
    snps = colnames(X)[cs$cs[[j]]]
    indx = which(rownames(gwas) %in% snps)
    colors[indx] = cols[j]
    points(indx, -log10(gwas[indx, "p.value.spa"]), col = cols[j], pch = 20)
  }
  rm(gwas, res, X, fit)
  
  # AOA
  res = readRDS(paste0("/Users/nicholeyang/Downloads/survivalsusie/result/asthma_self_report/result202408/aoa/fit.susie.", region, ".rds"))
  gwas = readRDS(paste0("/Users/nicholeyang/downloads/survivalsusie/result/gwas_surv/aoa_gwas_", region, ".rds"))
  fit = res[[1]]
  X = res[[2]]
  class(fit) = "susie"
  cs <- susie_get_cs(fit, X)
  
  colors = rep("#C3C3C3", nrow(gwas))
  pvals = -log10(gwas[, "p.value.spa"])
  plot(pvals, col = colors, xlab = "SNP", ylab = "-log10(p-value)", cex = 0.8, pch = 20, main = paste0(region_name[i], ": AOA"), ylim = c(0, max(pvals, na.rm = TRUE)+0.1))
  for (j in 1:length(cs$cs)){
    snps = colnames(X)[cs$cs[[j]]]
    indx = which(rownames(gwas) %in% snps)
    colors[indx] = cols[j]
    points(indx, -log10(gwas[indx, "p.value.spa"]), col = cols[j], pch = 20)
  }
  rm(gwas, res, X, fit)
}
```

