---
title: "Top gwas signal summary"
author: "Yunqi Yang"
date: "7/3/2024"
output: html_document
---

```{r}
library(stringr)
```

```{r}
logistic.aoa <- list.files(path="/Users/nicholeyang/Downloads/survivalsusie/data/gwas_logistic_out/aoa", pattern = "\\.glm\\.logistic$", full.names = TRUE)
logistic.coa <- list.files(path="/Users/nicholeyang/Downloads/survivalsusie/data/gwas_logistic_out/coa", pattern = "\\.glm\\.logistic$", full.names = TRUE)

logistic <- list.files(path="/Users/nicholeyang/Downloads/survivalsusie/data/gwas_logistic_out/all", pattern = "\\.glm\\.logistic$", full.names = TRUE)
```

```{r}
dir = "/Users/nicholeyang/Downloads/survivalsusie/result/gwas_surv"
surv.aoa <- list.files(path = dir, pattern = "^aoa.*\\.rds$", full.names = TRUE)
surv.coa <- list.files(path = dir, pattern = "^coa.*\\.rds$", full.names = TRUE)
surv <- list.files(path = dir, pattern = "^all.*\\.rds$", full.names = TRUE)
```

### 1. All asthma
```{r}
## Based on logistic pvalue
pattern <- "chr[0-9XYM]+_[0-9]+_[0-9]+"
pval.all = data.frame(matrix(NA, nrow = length(logistic), ncol = 4))
colnames(pval.all) = c("region", "snp", "logistic", "coxph")
for (i in 1:length(logistic)){
  path = logistic[i]
  region = str_extract(path, pattern)
  gwas.logistic = read.csv(path, header = TRUE, sep = "\t")
  gwas.surv = readRDS(paste0(dir, "/all_gwas_", region, ".rds"))
  gwas.surv = data.frame(gwas.surv)
  gwas.surv$ID = sapply(1:nrow(gwas.surv), function(i) unlist(strsplit(rownames(gwas.surv)[i], "_"))[1])
  indx = which.min(gwas.logistic$P)
  snp = gwas.logistic$ID[indx]
  pval.all[i, ] = c(region, snp, -log10(gwas.logistic$P[indx]),
                   -log10(gwas.surv$p.value.spa[which(gwas.surv$ID == snp)]))
}
```

```{r}
## Based on survival pvalue
pattern <- "chr[0-9XYM]+_[0-9]+_[0-9]+"
pval.all2 = data.frame(matrix(NA, nrow = length(logistic), ncol = 4))
colnames(pval.all2) = c("region", "snp", "logistic", "coxph")
for (i in 1:length(logistic)){
  path = logistic[i]
  region = str_extract(path, pattern)
  gwas.logistic = read.csv(path, header = TRUE, sep = "\t")
  gwas.surv = readRDS(paste0(dir, "/all_gwas_", region, ".rds"))
  gwas.surv = data.frame(gwas.surv)
  gwas.surv$ID = sapply(1:nrow(gwas.surv), function(i) unlist(strsplit(rownames(gwas.surv)[i], "_"))[1])
  indx = which.min(gwas.surv$p.value.spa)
  snp = gwas.surv$ID[indx]
  pval.all2[i, ] = c(region, snp, -log10(gwas.logistic$P[which(gwas.logistic$ID == snp)]),
                   -log10(gwas.surv$p.value.spa[which(gwas.surv$ID == snp)]))
}
```

```{r}
snp_list = rbind(pval.all, pval.all2)
write.csv(snp_list, "/Users/nicholeyang/Downloads/survival-data-analysis/output/logistic_surv_comparison/top_signal_AA.csv")
```


### 2. COA

```{r}
## logistic signal
pattern <- "chr[0-9XYM]+_[0-9]+_[0-9]+"
pval.coa = data.frame(matrix(NA, nrow = length(logistic), ncol = 4))
colnames(pval.coa) = c("region", "snp", "logistic", "coxph")
for (i in 1:length(logistic.coa)){
  path = logistic.coa[i]
  region = str_extract(path, pattern)
  gwas.logistic = read.csv(path, header = TRUE, sep = "\t")
  gwas.surv = readRDS(paste0(dir, "/coa_gwas_", region, ".rds"))
  gwas.surv = data.frame(gwas.surv)
  gwas.surv$ID = sapply(1:nrow(gwas.surv), function(i) unlist(strsplit(rownames(gwas.surv)[i], "_"))[1])
  indx = which.min(gwas.logistic$P)
  snp = gwas.logistic$ID[indx]
  pval.coa[i, ] = c(region, snp, -log10(gwas.logistic$P[indx]),
                   -log10(gwas.surv$p.value.spa[which(gwas.surv$ID == snp)]))
}
```

```{r}
## survival signals
pattern <- "chr[0-9XYM]+_[0-9]+_[0-9]+"
pval.coa2 = data.frame(matrix(NA, nrow = length(logistic), ncol = 4))
colnames(pval.coa2) = c("region", "snp", "logistic", "coxph")
for (i in 1:length(logistic.coa)){
  path = logistic.coa[i]
  region = str_extract(path, pattern)
  gwas.logistic = read.csv(path, header = TRUE, sep = "\t")
  gwas.surv = readRDS(paste0(dir, "/coa_gwas_", region, ".rds"))
  gwas.surv = data.frame(gwas.surv)
  gwas.surv$ID = sapply(1:nrow(gwas.surv), function(i) unlist(strsplit(rownames(gwas.surv)[i], "_"))[1])
  indx = which.min(gwas.surv$p.value.spa)
  snp = gwas.surv$ID[indx]
  pval.coa2[i, ] = c(region, snp, -log10(gwas.logistic$P[which(gwas.logistic$ID == snp)]),
                   -log10(gwas.surv$p.value.spa[which(gwas.surv$ID == snp)]))
}
```


```{r}
snp_list = rbind(pval.coa, pval.coa2)
write.csv(snp_list, "/Users/nicholeyang/Downloads/survival-data-analysis/output/logistic_surv_comparison/top_signal_COA.csv")
```


### 3. AOA
```{r}
## logistic signals
pattern <- "chr[0-9XYM]+_[0-9]+_[0-9]+"
pval.aoa = data.frame(matrix(NA, nrow = length(logistic), ncol = 4))
colnames(pval.aoa) = c("region", "snp", "logistic", "coxph")
for (i in 1:length(logistic.aoa)){
  path = logistic.aoa[i]
  region = str_extract(path, pattern)
  gwas.logistic = read.csv(path, header = TRUE, sep = "\t")
  gwas.surv = readRDS(paste0(dir, "/aoa_gwas_", region, ".rds"))
  gwas.surv = data.frame(gwas.surv)
  gwas.surv$ID = sapply(1:nrow(gwas.surv), function(i) unlist(strsplit(rownames(gwas.surv)[i], "_"))[1])
  indx = which.min(gwas.logistic$P)
  snp = gwas.logistic$ID[indx]
  pval.aoa[i, ] = c(region, snp, -log10(gwas.logistic$P[indx]),
                   -log10(gwas.surv$p.value.spa[which(gwas.surv$ID == snp)]))
}
```

```{r}
## survival signals
pattern <- "chr[0-9XYM]+_[0-9]+_[0-9]+"
pval.aoa2 = data.frame(matrix(NA, nrow = length(logistic), ncol = 4))
colnames(pval.aoa2) = c("region", "snp", "logistic", "coxph")
for (i in 1:length(logistic.aoa)){
  path = logistic.aoa[i]
  region = str_extract(path, pattern)
  gwas.logistic = read.csv(path, header = TRUE, sep = "\t")
  gwas.surv = readRDS(paste0(dir, "/aoa_gwas_", region, ".rds"))
  gwas.surv = data.frame(gwas.surv)
  gwas.surv$ID = sapply(1:nrow(gwas.surv), function(i) unlist(strsplit(rownames(gwas.surv)[i], "_"))[1])
  indx = which.min(gwas.surv$p.value.spa)
  snp = gwas.surv$ID[indx]
  pval.aoa2[i, ] = c(region, snp, -log10(gwas.logistic$P[which(gwas.logistic$ID == snp)]),
                   -log10(gwas.surv$p.value.spa[which(gwas.surv$ID == snp)]))
}
```

```{r}
snp_list = rbind(pval.aoa, pval.aoa2)
write.csv(snp_list, "/Users/nicholeyang/Downloads/survival-data-analysis/output/logistic_surv_comparison/top_signal_AOA.csv")
```

### Likelihood ratios of top signals

```{r}
res.AA = read.csv("/Users/nicholeyang/Downloads/survival-data-analysis/output/logistic_surv_comparison/top_signal_LR_AA.csv", row.names = "X")

res.COA = read.csv("/Users/nicholeyang/Downloads/survival-data-analysis/output/logistic_surv_comparison/top_signal_LR_COA.csv", row.names = "X")

res.AOA = read.csv("/Users/nicholeyang/Downloads/survival-data-analysis/output/logistic_surv_comparison/top_signal_LR_AOA.csv", row.names = "X")
```

```{r fig.width=10, fig.height=4}


pdf("/Users/nicholeyang/Downloads/survival-data-analysis/output/top_signal.pdf", height = 4, width = 8)
par(mfrow = c(1,3))

indx.remove = which(res.AA$region %in% c("chr2_236400001_242193529", "chr12_54500001_56200000", "chr19_31900001_35100000"))
plot(res.AA$logistic.1[-indx.remove], res.AA$survival[-indx.remove], pch = 20, xlab = "Logistic log(LR)", ylab = "CoxPH log(LR)", main = "AA")
abline(a = 0, b = 1, col = "red")

indx.remove = which(res.COA$region %in% c("chr2_236400001_242193529", "chr12_54500001_56200000", "chr19_31900001_35100000"))
plot(res.COA$logistic.1[-indx.remove], res.COA$survival[-indx.remove], pch = 20, xlab = "Logistic log(LR)", ylab = "CoxPH log(LR)", main = "COA")
abline(a = 0, b = 1, col = "red")

indx.remove = which(res.AOA$region %in% c("chr2_236400001_242193529", "chr12_54500001_56200000", "chr19_31900001_35100000"))
plot(res.AOA$logistic.1[-indx.remove], res.AOA$survival[-indx.remove], pch = 20, xlab = "Logistic log(LR)", ylab = "CoxPH log(LR)", main = "AOA")
abline(a = 0, b = 1, col = "red")

```


```{r}
par(mfrow = c(1,3))
plot(res.AA$logistic, res.AA$coxph)
abline(a = 0, b = 1, col = "red")
plot(res.AOA$logistic, res.AOA$coxph)
abline(a = 0, b = 1, col = "red")
plot(res.COA$logistic, res.COA$coxph)
abline(a = 0, b = 1, col = "red")
```

