---
title: "Asthma: logistic gwas"
author: "Yunqi Yang"
date: "6/13/2024"
output: html_document
---

## Description:

Logistic gwas result for all asthma, childhood asthma and adulthood asthma


```{r}
file.aoa <- list.files(path="/Users/nicholeyang/Downloads/survivalsusie/data/gwas_logistic_out/aoa", pattern = "\\.glm\\.logistic$", full.names = TRUE)
file.coa <- list.files(path="/Users/nicholeyang/Downloads/survivalsusie/data/gwas_logistic_out/coa", pattern = "\\.glm\\.logistic$", full.names = TRUE)

file <- list.files(path="/Users/nicholeyang/Downloads/survivalsusie/data/gwas_logistic_out/all", pattern = "\\.glm\\.logistic$", full.names = TRUE)
```

```{r fig.width=10, fig.height=20}

par(mfrow = c(6,2))
for (i in 1:length(file)){
  region = file[i]
  region_name = strsplit(region, "/")[[1]][9]
  gwas = read.csv(region, header = TRUE, sep = "\t")
  plot(gwas$POS, -log10(gwas$P), pch = 20, cex = 0.5, main = region_name, ylab = "log10-pval", xlab = "Position")
}

```


```{r fig.width=10, fig.height=20}

par(mfrow = c(6,2))
for (i in 1:length(file.aoa)){
  region = file.aoa[i]
  region_name = strsplit(region, "/")[[1]][9]
  gwas.aoa = read.csv(region, header = TRUE, sep = "\t")
  gwas.coa = read.csv(region, header = TRUE, sep = "\t")
  ymin = min(log10(gwas.aoa$P)) - 1
  ymax = max(-log10(gwas.coa$P)) + 2
  plot(gwas.aoa$POS, log10(gwas.aoa$P), ylim = c(ymin, ymax), pch = 20, cex = 0.5, col = "#2c7fb8", main = region_name, ylab = "log10-pval", xlab = "Position")
  points(gwas.coa$POS, -log10(gwas.coa$P), pch = 20, cex = 0.5, col = "#de2d26")
  legend("topright", legend = c("COA", "AOA"), col = c("#de2d26", "#2c7fb8"), pch = 20)
}

```




